{{- if .Values.kafka.listeners.scram.enableLECerts }}
apiVersion: v1
kind: Secret
metadata:
 name: {{ .Values.kafka.name }}-scram-certificate
 namespace: {{ .Values.namespace }}
 annotations:
   reflector.v1.k8s.emberstack.com/reflects: "openshift-ingress/{{ .Values.kafka.listeners.scram.routerShardSecret }}"
{{- end }}
